# Generated by Django 5.0.1 on 2024-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
    ]
