# Generated by Django 5.0.1 on 2024-01-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
