# Generated by Django 5.0.1 on 2024-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
